#!/usr/bin/env node
// Turn snarkjs verification_key.json into the embedded Rust verifying key for the
// Stylus CreditVerifier. Run after circuits/build.sh:
//
//   node circuits/gen-vk.mjs > contracts/credit-verifier/src/vk.rs
//
// G2 points are emitted as (c0, c1) = (real, imaginary), matching ark Fq2::new(c0, c1)
// and agent/src/proof.ts. snarkjs stores G2 in [c0, c1] order in the JSON, so no swap.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const VK_PATH = fileURLToPath(new URL("./build/verification_key.json", import.meta.url));
const vk = JSON.parse(readFileSync(VK_PATH, "utf8"));

const hex = (dec) => BigInt(dec).toString(16);
const g1 = (p) => `g1("${hex(p[0])}", "${hex(p[1])}")`;
// p = [[x_c0, x_c1], [y_c0, y_c1], [1,0]]
const g2 = (p) => `g2("${hex(p[0][0])}", "${hex(p[0][1])}", "${hex(p[1][0])}", "${hex(p[1][1])}")`;

const ic = vk.IC.map((p) => `        ${g1(p)},`).join("\n");

process.stdout.write(`//! Embedded Groth16 verifying key for the Cobra credit circuit.
//! GENERATED by circuits/gen-vk.mjs from circuits/build/verification_key.json. Do not edit.
//! nPublic = ${vk.nPublic}  (root, threshold, clientCommitment, epoch)

use ark_bn254::{Bn254, Fq, Fq2, G1Affine, G2Affine};
use ark_ff::PrimeField;
use ark_groth16::VerifyingKey;
use alloc::vec::Vec;
use alloc::vec;

fn fq(hex: &str) -> Fq {
    Fq::from_be_bytes_mod_order(&decode_hex(hex))
}
fn g1(x: &str, y: &str) -> G1Affine {
    G1Affine::new_unchecked(fq(x), fq(y))
}
fn g2(x0: &str, x1: &str, y0: &str, y1: &str) -> G2Affine {
    G2Affine::new_unchecked(Fq2::new(fq(x0), fq(x1)), Fq2::new(fq(y0), fq(y1)))
}
fn decode_hex(s: &str) -> Vec<u8> {
    let s = if s.len() % 2 == 1 { alloc::format!("0{s}") } else { alloc::string::String::from(s) };
    let b = s.as_bytes();
    let h = |c: u8| match c { b'0'..=b'9' => c - b'0', b'a'..=b'f' => c - b'a' + 10, b'A'..=b'F' => c - b'A' + 10, _ => 0 };
    let mut out = Vec::with_capacity(b.len() / 2);
    let mut i = 0;
    while i + 1 < b.len() + 1 && i + 1 <= b.len() {
        out.push((h(b[i]) << 4) | h(b[i + 1]));
        i += 2;
    }
    out
}

pub fn verifying_key() -> VerifyingKey<Bn254> {
    VerifyingKey {
        alpha_g1: ${g1(vk.vk_alpha_1)},
        beta_g2: ${g2(vk.vk_beta_2)},
        gamma_g2: ${g2(vk.vk_gamma_2)},
        delta_g2: ${g2(vk.vk_delta_2)},
        gamma_abc_g1: vec![
${ic}
        ],
    }
}
`);
