#!/usr/bin/env node
// Turn snarkjs verification_key.json into the embedded Rust verifying key for the Stylus
// CreditVerifier (precompile layout). Run after circuits/build.sh:
//
//   node circuits/gen-vk.mjs > contracts/credit-verifier/src/vk.rs
//
// G2 points are emitted in the EVM precompile order [x.c1, x.c0, y.c1, y.c0] — i.e. snarkjs
// [[x.c0, x.c1], [y.c0, y.c1]] reordered, matching snarkjs's own Verifier.sol.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const VK_PATH = fileURLToPath(new URL("./build/verification_key.json", import.meta.url));
const vk = JSON.parse(readFileSync(VK_PATH, "utf8"));

const dec = (v) => BigInt(v).toString();
const g1 = (p) => `[u("${dec(p[0])}"), u("${dec(p[1])}")]`;
// snarkjs G2 p = [[x.c0, x.c1], [y.c0, y.c1], ..] -> precompile [x.c1, x.c0, y.c1, y.c0]
const g2 = (p) => `[u("${dec(p[0][1])}"), u("${dec(p[0][0])}"), u("${dec(p[1][1])}"), u("${dec(p[1][0])}")]`;
const ic = vk.IC.map((p) => `            ${g1(p)},`).join("\n");

process.stdout.write(`//! Embedded Groth16 verifying key (precompile layout: G2 as [x.c1, x.c0, y.c1, y.c0]).
//! GENERATED by circuits/gen-vk.mjs from circuits/build/verification_key.json. Do not edit.
//! nPublic = ${vk.nPublic}  (root, threshold, clientCommitment, epoch)

use alloy_primitives::U256;
use alloc::vec::Vec;

pub struct Vk {
    pub alpha: [U256; 2],
    pub beta: [U256; 4],
    pub gamma: [U256; 4],
    pub delta: [U256; 4],
    pub ic: Vec<[U256; 2]>,
}

#[inline]
fn u(s: &str) -> U256 {
    U256::from_str_radix(s, 10).unwrap()
}

pub fn verifying_key() -> Vk {
    Vk {
        alpha: ${g1(vk.vk_alpha_1)},
        beta: ${g2(vk.vk_beta_2)},
        gamma: ${g2(vk.vk_gamma_2)},
        delta: ${g2(vk.vk_delta_2)},
        ic: alloc::vec![
${ic}
        ],
    }
}
`);
